Merge DEV to Master on merge success
Added steps to checkout master branch and merge dev into master in CI/CD workflow.

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -27,6 +27,19 @@ jobs:
     - name: Run tests
       run: dotnet test --no-build --verbosity normal
 
+    - name: Checkout master branch
+      run: git checkout master
+      
+    - name: Merge dev into master
+      run: |
+       git config user.name "${{ secrets.DOCKER_USERNAME }}"
+       git config user.email "${{ secrets.GIT_USER_EMAIL }}"
+        git fetch origin dev
+        git merge origin/dev --no-ff --no-commit || (echo "Merge conflict detected. Aborting." && exit 1)
+        git commit -m "Auto-merged dev into master [skip ci]" || echo "Nothing to commit"
+        git push origin master
+
+
     - name: Build CatalogService Docker image
       working-directory: ./CatalogService
       run: docker build -t soumyatajena/catalogservice:latest .
